import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Store Demo</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href='https://nextjs.org'>Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <ul className={styles.grid}>
          <li className={styles.card}>
            <a href='#'>
              <img src='/images/tshirt.jpg' alt='Adidas Tshirt' />
              <h3>Adidas Tshirt</h3>
              <p>
                Bring Cosmo the Adidasfish to your wardrobe with this high
                quality tshirt.
              </p>
            </a>
          </li>

          <li className={styles.card}>
            <a href='#'>
              <img src='/images/stickers.jpg' alt='Adidas Stickers' />
              <h3>Adidas Stickers</h3>
              <p>
                Add some flare to your laptop with a sticker of Cosmo the Space
                Jellyfish.
              </p>
            </a>
          </li>

          <li className={styles.card}>
            <a href='#'>
              <img src='/images/combo.jpg' alt='Adidas Combo Pack' />
              <h3>Adidas Combo</h3>
              <p>
                Show your love for Cosmo with a tshirt and sticker combo pack!
              </p>
            </a>
          </li>
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <img src='/vercel.svg' alt='Vercel Logo' className={styles.logo} />
        </a>
      </footer>
    </div>
  );
};

export default Home;
